version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8003:8003"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8003"
    environment:
      - DB_HOST=imdb
      - DB_NAME=imdb
      - DB_USER=imdbuser
      - DB_PASS=imdbpass
    depends_on:
      - imdb

  imdb:
    image: postgres:13-alpine
    volumes:
      - imdb-data:/var/lib/postgresql/data
    expose:
      - '5434'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=imdb
      - POSTGRES_USER=imdbuser
      - POSTGRES_PASSWORD=imdbpass

volumes:
  imdb-data:
