# Generated by Django 4.2.6 on 2023-11-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
