# Generated by Django 4.2.6 on 2023-11-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'password'], name='user_email_password_idx'),
        ),
    ]
